In [5]:
"""
Phase 5: Evaluation

This file compares different review strategies by measuring regret.
Regret is defined as customers whose tolerance drops below a critical
threshold while they were not reviewed.
"""

'\nPhase 5: Evaluation\n\nThis file compares different review strategies by measuring regret.\nRegret is defined as customers whose tolerance drops below a critical\nthreshold while they were not reviewed.\n'

In [6]:
import pandas as pd
import numpy as np

In [ ]:
import sys
import os

PROJECT_ROOT = os.path.abspath("..")
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)


In [ ]:
from config import (
    N_CUSTOMERS,
    NUM_WEEKS,
    K,
    DECAY_RATE,
    RECOVERY_RATE,
    COOLDOWN_WINDOW,
    COOLDOWN_PENALTY,
    REGRET_THRESHOLD,
    SEEDS
)

In [8]:
from simulation.simulate_week_for_export import initialize_world,advance_one_week

In [9]:
df = initialize_world()

In [ ]:
weekly_regret_random = []
for week in range(NUM_WEEKS):
    df['reviewed'] = False
    review_id = np.random.choice(df.index,size=K,replace = False)
    df.loc[review_id,'reviewed'] = True
    df = advance_one_week(df,DECAY_RATE,RECOVERY_RATE)
    regret_count = ((df['tolerance'] < REGRET_THRESHOLD) & (~df['reviewed'])).sum()
    weekly_regret_random.append(regret_count)

total_regret_random = sum(weekly_regret_random)

week : 0| 
[76  3 63 69 74 37 11 47 13 40] | 
Week ended
week : 1| 
[97 28 35 63 10 72 49 66 27 71] | 
Week ended
week : 2| 
[41 40  4 81 42 58 53 22 32 92] | 
Week ended
week : 3| 
[ 2 63 19 51 27  5  9 38 24 90] | 
Week ended
week : 4| 
[ 1 36 90 28 53 66 67 45 39 33] | 
Week ended
week : 5| 
[77  1 23 71 12 31 73 40  8 50] | 
Week ended
week : 6| 
[10 17 98 11 25 52 69 46  3 33] | 
Week ended
week : 7| 
[90 53 81 68 14 48  3 79 95 29] | 
Week ended
week : 8| 
[ 9 20 86 58 15 74 87 14 47 66] | 
Week ended
week : 9| 
[65 14 92  5 44 16 97 38 91 60] | 
Week ended


In [11]:
df = initialize_world()

In [ ]:
weekly_regret_urgency = []
for week in range(NUM_WEEKS):
    df['reviewed'] = False
    review_id = (df.sort_values('urgency_score',ascending=False).head(K).index)
    df.loc[review_id,'reviewed'] = True
    df = advance_one_week(df,DECAY_RATE,RECOVERY_RATE)
    regret_count = ((df['tolerance'] < REGRET_THRESHOLD) & (~df['reviewed'])).sum()
    weekly_regret_urgency.append(regret_count)

total_regret_urgency = sum(weekly_regret_urgency)

week : 0| 
Index([71, 93, 37, 88, 15, 46, 42, 24, 25, 38], dtype='int64') | 
Week ended
week : 1| 
Index([30, 99, 96, 89, 69, 23, 53, 44, 68, 21], dtype='int64') | 
Week ended
week : 2| 
Index([54, 93, 57, 22, 96, 83, 62, 27, 17, 46], dtype='int64') | 
Week ended
week : 3| 
Index([23, 85, 96, 45, 88, 80, 93, 87, 70, 4], dtype='int64') | 
Week ended
week : 4| 
Index([21, 17, 18, 3, 64, 85, 40, 75, 42, 54], dtype='int64') | 
Week ended
week : 5| 
Index([30, 88, 45, 22, 66, 70, 4, 99, 15, 83], dtype='int64') | 
Week ended
week : 6| 
Index([93, 28, 25, 69, 22, 77, 40, 96, 80, 87], dtype='int64') | 
Week ended
week : 7| 
Index([23, 30, 85, 45, 70, 88, 1, 82, 57, 71], dtype='int64') | 
Week ended
week : 8| 
Index([53, 47, 14, 70, 78, 87, 88, 27, 11, 45], dtype='int64') | 
Week ended
week : 9| 
Index([40, 15, 34, 55, 9, 22, 23, 1, 44, 87], dtype='int64') | 
Week ended


In [13]:
print(f"Random Selection : {total_regret_random}")
print(f"Urgency Selection : {total_regret_urgency}")

Random Selection : 240
Urgency Selection : 291


### In our base system, urgency-based prioritization consistently produced higher cumulative regret than random selection.